version: '3'
services:
  app_gpu0:
    image: audio-split-server-v3:latest
    environment:
      - CUDA_VISIBLE_DEVICES=0
    ports:
      - "7005:7005"
    command: [ "uvicorn", "main:app", "--host", "0.0.0.0", "--port", "7005", "--workers", "3" ]
  app_gpu1:
    image: audio-split-server-v3:latest
    environment:
      - CUDA_VISIBLE_DEVICES=1
    ports:
      - "7006:7005"
    command: [ "uvicorn", "main:app", "--host", "0.0.0.0", "--port", "7005", "--workers", "3" ]